# Generated by Django 2.2.5 on 2020-03-11 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20191128_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_read_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='message.Message', verbose_name='последнее прочитанное сообщение'),
        ),
    ]
