# Generated by Django 2.2.5 on 2019-12-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='some avatar', verbose_name='аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(default='some nick', max_length=16, verbose_name='никнейм пользователя'),
        ),
    ]
