# Generated by Django 2.2.5 on 2019-12-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191228_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='some name', max_length=32, verbose_name='имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=16, verbose_name='никнейм пользователя'),
        ),
    ]
