# Generated by Django 2.2.5 on 2019-11-19 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_attachement_chat'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachement',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='сообщение, в котором содержится вложение'),
        ),
    ]
